name: mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  mysql1: ^0.20.0


  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  http: ^1.2.0
  dio: ^5.4.1
  firebase_core: ^2.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
