name: mobile
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  mysql1: ^0.20.0

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_database: ^10.4.9
  random_string: ^2.1.0
  google_fonts: ^4.0.0
  image_picker: ^1.0.8
  file_picker: ^8.0.0+1
  google_maps_flutter: ^2.5.3
  firebase_storage: ^11.6.9
  flutter_staggered_grid_view: ^0.7.0
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
