// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wMrC-_DDEkT1pqkNPXU7kPMukYM-KsE',
    appId: '1:297419808189:web:b6a8f86ffc341dbdb6c6d4',
    messagingSenderId: '297419808189',
    projectId: 'mobilelms-8be5d',
    authDomain: 'mobilelms-8be5d.firebaseapp.com',
    storageBucket: 'mobilelms-8be5d.appspot.com',
    measurementId: 'G-2CCYT6BZ3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd_auWqq4VlMw02vg7WLJtpY4xvqsS8rg',
    appId: '1:297419808189:android:ca44ba920d36c5c6b6c6d4',
    messagingSenderId: '297419808189',
    projectId: 'mobilelms-8be5d',
    storageBucket: 'mobilelms-8be5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrmWO9JemBB_Cz1TuVYxPEPHLxMqZp90',
    appId: '1:297419808189:ios:bf5357f426c946cdb6c6d4',
    messagingSenderId: '297419808189',
    projectId: 'mobilelms-8be5d',
    storageBucket: 'mobilelms-8be5d.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrmWO9JemBB_Cz1TuVYxPEPHLxMqZp90',
    appId: '1:297419808189:ios:bf5357f426c946cdb6c6d4',
    messagingSenderId: '297419808189',
    projectId: 'mobilelms-8be5d',
    storageBucket: 'mobilelms-8be5d.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2wMrC-_DDEkT1pqkNPXU7kPMukYM-KsE',
    appId: '1:297419808189:web:2f6a4dd6db0efb37b6c6d4',
    messagingSenderId: '297419808189',
    projectId: 'mobilelms-8be5d',
    authDomain: 'mobilelms-8be5d.firebaseapp.com',
    storageBucket: 'mobilelms-8be5d.appspot.com',
    measurementId: 'G-WS71FVXF7V',
  );
}
